Add routes
Diary-SPO/bun-elysia pull request #1
Opened 2023-10-10 18:30 UTC by Kopchan

2023-10-10 20:40 UTC, scffs commented
В рамках PR перенести чистую логику роутов без доп. функционала

2023-10-11 14:16 UTC, scffs requested changes

2023-10-11 14:42 UTC, scffs commented on src/routes/lessons.route.ts
> +    .get('/:id/:startDate/:endDate', ({ params: { id, startDate, endDate } }) => {
Именно саму функцию `({ params: { id, startDate, endDate } }) => {}...` 

То есть что-то типа:
```ts
const getLessons =  (id, startDate, endDate) => {
  // TODO: Сделать получение данных расписания
}

const router = new Elysia()
// Передать параметры в функцию
 .get('/:id/:startDate/:endDate', getLessons());
```

2023-10-11 17:36 UTC, Kopchan commented on src/routes/lessons.route.ts
> +    .get('/:id/:startDate/:endDate', ({ params: { id, startDate, endDate } }) => {
Хорошо, сделаю

2023-10-11 17:53 UTC, Kopchan commented on src/routes/lessons.route.ts
> +    .get('/:id/:startDate/:endDate', ({ params: { id, startDate, endDate } }) => {
Ну, не осилил
![изображение](https://github.com/Diary-SPO/bun-elysia/assets/83940856/2ff1f950-9064-4864-87b8-e02d1e7cb759)

2023-10-11 17:58 UTC, scffs requested changes

2023-10-11 17:58 UTC, scffs commented on src/routes/lessons.route.ts
> +  .get('/lessons/:id/:startDate/:endDate', async ({ request, set, params: { id, startDate, endDate } }) => {
Вынеси в функцию пж

2023-10-11 18:01 UTC, scffs commented on src/routes/lessons.route.ts
> +  .get('/lessons/:id/:startDate/:endDate', async ({ request, set, params: { id, startDate, endDate } }) => {
UPD: требуется помощь + чтение доки

2023-10-12 02:41 UTC, Kopchan commented on src/routes/lessons.route.ts
> +  .get('/lessons/:id/:startDate/:endDate', async ({ request, set, params: { id, startDate, endDate } }) => {
Что-то не получается с таким кодом ```bash
const getLessons = async (request: Request, set: object, id: string, startDate: string, endDate: string): Handler<MergeSchema<UnwrapRoute<InputSchema<never>, any>, any>, { request: any; store: any; }, "/lessons/:id/:startDate/:endDate"> => {
  // Функция
}
const router = new Elysia()
  .get('/lessons/:id/:startDate/:endDate', getLessons(request, set, id, startDate, endDate))
```

2023-10-12 07:03 UTC, scffs requested changes

2023-10-12 07:20 UTC, merged